apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: alushtaa/homework:0.5
      volumeMounts:
      - name: app
        mountPath: /app
      ports:
        - containerPort: 8000
  volumes:
  - name: app
    emptyDir: {}
  initContainers:
    - name: init
      image: busybox:1.35.0
      volumeMounts:
      - name: app
        mountPath: /app
      command: ['sh', '-c', 'wget --no-check-certificate -O- https://tinyurl.com/otus-k8s-intro | sh']
